version: "2.7"
services:
  account:
    build: account
    image: account:latest
    restart: always
    volumes:
      - ./storage/account:/opt/account/db
  prescription:
    build: prescription
    image: prescription:latest
    restart: always
    volumes:
      - ./storage/prescription:/opt/prescription/db
  gateway:
    image: nginx
    depends_on:
      - account
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"