# Generated by Django 4.0 on 2021-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='drug_list',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
