# Generated by Django 4.0 on 2021-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scription', '0002_prescription_drug_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='drug_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
